# Generated by Django 4.0 on 2021-12-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
                ('img_url', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('source', models.TextField(max_length=200)),
            ],
        ),
    ]
